### ISSUE TITLE
[EPIC] Dashboards-as-code for UCX

### ISSUE THREAD

**Issue by nfx** [databrickslabs/lsql#138]
Subset of #106 

- [x] https://github.com/databrickslabs/lsql/issues/141
- [x] https://github.com/databrickslabs/lsql/issues/112
- [x] https://github.com/databrickslabs/lsql/issues/130
- [ ] https://github.com/databrickslabs/lsql/issues/131
- [x] https://github.com/databrickslabs/lsql/issues/148
- [x] https://github.com/databrickslabs/lsql/issues/133
- [ ] https://github.com/databrickslabs/lsql/issues/135
- [ ] https://github.com/databrickslabs/lsql/issues/127
- [ ] https://github.com/databrickslabs/lsql/issues/137
- [ ] https://github.com/databrickslabs/lsql/issues/110
- [x] https://github.com/databrickslabs/lsql/issues/114
- [ ] https://github.com/databrickslabs/lsql/issues/158
- [ ] https://github.com/databrickslabs/lsql/issues/159
- [ ] https://github.com/databrickslabs/lsql/issues/163
- [ ] https://github.com/databrickslabs/lsql/issues/165
- [ ] https://github.com/databrickslabs/lsql/issues/169
- [ ] https://github.com/databrickslabs/lsql/issues/175
- [ ] https://github.com/databrickslabs/lsql/issues/187
- [ ] https://github.com/databrickslabs/lsql/issues/191
- [x] https://github.com/databrickslabs/lsql/issues/122
